import React, { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';

const DISTRICTS = [
  { id: '01', name: 'Living Canopy', signal: 'ECOLOGY', copy: 'Architecture and landscape are treated as one civic surface: shade, food systems, biodiversity, public space, and building envelopes work together rather than competing for leftover land.' },
  { id: '02', name: 'Blue Arteries', signal: 'WATER', copy: 'Water is visible civic infrastructure. Channels, retention landscapes, wetlands, cooling corridors, and public edges become part of the city’s spatial identity rather than buried engineering.' },
  { id: '03', name: 'Elevated Circulation', signal: 'MOBILITY', copy: 'High-capacity movement is lifted and disciplined so the ground plane can remain humane: walking, cycling, neighborhood access, trees, gathering space, and local commerce stay legible.' },
  { id: '04', name: 'Maker Spine', signal: 'PRODUCTION', copy: 'Research, light manufacturing, circular-material systems, logistics, and skills infrastructure are clustered into productive districts instead of being pushed outside the civic story.' },
  { id: '05', name: 'Cathedral of Light', signal: 'CIVIC MEMORY', copy: 'A monumental public anchor for reflection, ceremony, learning, and collective memory. The visual language is luminous and civic—not a claim of supernatural function.' },
] as const;

function CityField({ active }: { active: number }) {
  return <div className="relative aspect-[16/10] overflow-hidden border border-[#d8aa43]/20 bg-[#03101c]">
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_18%,rgba(216,170,67,.14),transparent_24%),linear-gradient(180deg,#061b2f_0%,#05243a_45%,#03111c_100%)]" />
    <div className="absolute bottom-0 left-0 right-0 h-[31%] bg-[linear-gradient(180deg,rgba(13,104,129,.38),rgba(4,31,46,.92))]" />
    {Array.from({length:13}).map((_,i)=><motion.div key={i} className="absolute bottom-[28%] border border-[#d8aa43]/25 bg-[linear-gradient(180deg,rgba(216,170,67,.11),rgba(5,20,31,.92))]" style={{left:`${4+i*7.4}%`,width:`${4.2+(i%3)*1.8}%`,height:`${18+(i*11)%38}%`,clipPath:i%4===0?'polygon(50% 0,100% 18%,88% 100%,12% 100%,0 18%)':i%3===0?'polygon(20% 0,80% 0,100% 100%,0 100%)':'none'}} animate={{borderColor:i===active*2?['rgba(216,170,67,.25)','rgba(216,170,67,.8)','rgba(216,170,67,.25)']:'rgba(216,170,67,.2)'}} transition={{duration:3.5,repeat:Infinity}} />)}
    <motion.div className="absolute left-[8%] right-[8%] top-[50%] h-[3px] bg-gradient-to-r from-transparent via-[#7cc7ff]/80 to-transparent" animate={{opacity:[.35,.9,.35],scaleX:[.9,1,.92]}} transition={{duration:4,repeat:Infinity}} />
    <motion.div className="absolute left-[15%] right-[15%] top-[57%] h-px bg-[#d8aa43]/55" animate={{x:['-2%','2%','-2%']}} transition={{duration:8,repeat:Infinity}} />
    {Array.from({length:18}).map((_,i)=><span key={i} className="absolute h-1.5 w-1.5 rounded-full bg-[#63c583]/70" style={{left:`${5+(i*17)%90}%`,bottom:`${6+(i*13)%22}%`}}/>)}
    <div className="absolute bottom-5 left-6 right-6 flex justify-between text-[9px] uppercase tracking-[.22em] text-white/30"><span>Nu Ta Meri /// conceptual civic field</span><span>land · water · movement · memory</span></div>
  </div>;
}

export default function NuTaMeri() {
  const [active, setActive] = useState(0);
  return <div className="min-h-screen bg-[#020b13] text-[#f4f0e6]">
    <section className="relative min-h-[94vh] overflow-hidden border-b border-white/10">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_78%_18%,rgba(216,170,67,.13),transparent_25%),radial-gradient(circle_at_16%_70%,rgba(45,139,177,.17),transparent_28%),linear-gradient(135deg,#02080e,#061a2a_62%,#02070c)]" />
      <div className="relative z-10 mx-auto grid min-h-[94vh] max-w-[1560px] items-center gap-16 px-6 py-28 lg:grid-cols-[.86fr_1.14fr] lg:px-14">
        <div><p className="mb-8 text-[10px] uppercase tracking-[.34em] text-[#d8aa43]">Civilization layer /// Nu Ta Meri</p><h1 className="mb-8 text-[clamp(4.2rem,9vw,9rem)] leading-[.78] tracking-[-.05em]" style={{fontFamily:'"Cormorant Garamond",serif'}}>A city that<br/><span className="text-[#7cc7ff]">remembers.</span></h1><p className="max-w-[700px] border-l border-[#d8aa43]/35 pl-6 text-[clamp(1.15rem,2vw,1.65rem)] leading-[1.5] text-white/64">Nu Ta Meri is TRAI’s regenerative city vision: living architecture, visible water systems, elevated circulation, productive districts, ecological infrastructure, and civic memory organized as one coherent urban organism.</p><div className="mt-10 flex flex-wrap gap-3 text-[9px] uppercase tracking-[.19em] text-white/38"><span className="border border-white/10 px-4 py-2">blue-gold civic geometry</span><span className="border border-white/10 px-4 py-2">carbon-negative ambition</span><span className="border border-white/10 px-4 py-2">human ground plane</span></div></div>
        <CityField active={active}/>
      </div>
    </section>

    <section className="border-b border-white/10 py-28"><div className="mx-auto max-w-[1560px] px-6 lg:px-14"><div className="mb-14 grid gap-8 lg:grid-cols-[.72fr_1.28fr] lg:items-end"><div><p className="mb-4 text-[10px] uppercase tracking-[.3em] text-[#7cc7ff]">Five civic movements</p><h2 className="text-[clamp(2.7rem,5vw,5.2rem)] leading-[.94]" style={{fontFamily:'"Cormorant Garamond",serif'}}>The city is read through systems, not towers.</h2></div><p className="max-w-[680px] text-lg leading-8 text-white/48 lg:justify-self-end">The uploaded visual boards establish the scale—monumental, green, water-rich, blue-gold, elevated, ceremonial. The deeper source material adds the reason: ecology, mobility, production, public life, and memory must reinforce each other.</p></div>
      <div className="grid gap-8 lg:grid-cols-[.82fr_1.18fr]"><div className="space-y-2">{DISTRICTS.map((d,i)=><button key={d.id} onClick={()=>setActive(i)} className={`w-full border px-5 py-5 text-left transition ${active===i?'border-[#d8aa43]/45 bg-[#d8aa43]/[.05]':'border-white/10 hover:border-white/20'}`}><div className="flex justify-between text-[9px] uppercase tracking-[.2em] text-white/30"><span>{d.id}</span><span>{d.signal}</span></div><div className="mt-2 text-2xl" style={{fontFamily:'"Cormorant Garamond",serif'}}>{d.name}</div></button>)}</div><div className="border border-[#7cc7ff]/15 bg-[#041421] p-8 md:p-12"><AnimatePresence mode="wait"><motion.div key={active} initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}}><p className="mb-4 text-[10px] uppercase tracking-[.25em] text-[#7cc7ff]">{DISTRICTS[active].signal}</p><h3 className="mb-6 text-[clamp(2.7rem,5vw,5rem)] leading-[.92]" style={{fontFamily:'"Cormorant Garamond",serif'}}>{DISTRICTS[active].name}</h3><p className="max-w-[760px] text-lg leading-8 text-white/55">{DISTRICTS[active].copy}</p></motion.div></AnimatePresence></div></div>
    </div></section>

    <section className="border-b border-white/10 bg-[#041421] py-28"><div className="mx-auto grid max-w-[1560px] gap-12 px-6 lg:grid-cols-3 lg:px-14"><div><p className="mb-3 text-[9px] uppercase tracking-[.25em] text-[#d8aa43]">Movement</p><h3 className="mb-4 text-3xl" style={{fontFamily:'"Cormorant Garamond",serif'}}>Mela Nation as vessels</h3><p className="text-base leading-7 text-white/47">Community routes, last-mile logistics, and city circulation become one mobility system rather than separate transport products.</p><a href="/mela-nation" className="mt-6 inline-block text-[9px] uppercase tracking-[.2em] text-[#7cc7ff]">Enter Mela Nation →</a></div><div><p className="mb-3 text-[9px] uppercase tracking-[.25em] text-[#d8aa43]">Identity</p><h3 className="mb-4 text-3xl" style={{fontFamily:'"Cormorant Garamond",serif'}}>MeLaNiNa as civic surface</h3><p className="text-base leading-7 text-white/47">Fashion, textile, cultural expression, and material identity give the organism a public skin inside the larger city context.</p><a href="/melanina" className="mt-6 inline-block text-[9px] uppercase tracking-[.2em] text-[#7cc7ff]">Enter MeLaNiNa →</a></div><div><p className="mb-3 text-[9px] uppercase tracking-[.25em] text-[#d8aa43]">Infrastructure</p><h3 className="mb-4 text-3xl" style={{fontFamily:'"Cormorant Garamond",serif'}}>TRAI as operating organism</h3><p className="text-base leading-7 text-white/47">Materials, intelligence, mobility, identity, access, nourishment, and regenerative return are staged as interdependent civic systems.</p><a href="/" className="mt-6 inline-block text-[9px] uppercase tracking-[.2em] text-[#7cc7ff]">Return to the organism →</a></div></div></section>

    <section className="py-24"><div className="mx-auto max-w-[1100px] px-6 text-center lg:px-14"><p className="mb-4 text-[9px] uppercase tracking-[.28em] text-[#d8aa43]">Development posture</p><p className="text-lg leading-8 text-white/48">Nu Ta Meri is presented here as a city vision and systems-design framework. The architectural, transit, ecological, and civic imagery is conceptual and should not be read as built infrastructure, approved construction, or a guarantee of future performance.</p></div></section>
  </div>;
}
